version: '3.8'

services:
  backend:
    build: ./backend
    container_name: culinary_academy_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - culinary-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: culinary_academy_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - culinary-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: culinary_academy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    networks:
      - culinary-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: culinary_academy_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - culinary-network
    restart: unless-stopped

networks:

  culinary-network:
    driver: bridge

volumes:
  postgres_data: